spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/michelet_db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        default_schema: restaurant_service

  eureka:
    client:
      enabled: ${EUREKA_CLIENT_ENABLED:false}