server:
  port: 19300

spring:
  application:
    name: restaurant-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://db:5432/michelet_db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # restaurant-service 전용 schema를 사용
        default_schema: restaurant_service
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka-server:8761/eureka/}