spring:
  application:
    name: restaurant-service
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50

server:
  port: ${SERVER_PORT:19300}

management:
  endpoints:
    web:
      exposure:
        include: health,info

internal:
  auth:
    secret: ${INTERNAL_AUTH_SECRET}

feign:
  reservation-service:
    url: ${FEIGN_RESERVATION_SERVICE_URL:}